server:
  port: 8081

spring:
  redis:
    #配置Redis的主机地址
    host: 47.100.230.188
    #端口
    port: 6379
    #默认无密码
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时
    timeout: 2000